# ============================
# Configuracion general
# ============================
spring.application.name=certificados-app
server.port=8080

# ============================
# Base de datos MySQL (Localhost)
# ============================
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_academica?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=2403
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================
# JPA / Hibernate
# ============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ============================
# Servir el frontend Angular (arquitectura monolitica)
# ============================
spring.web.resources.static-locations=classpath:/static/
app.storage.upload-dir=build/test-uploads

# ============================
# CORS
# ============================
app.cors.allowed-origins=http://localhost:4200

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always